# favicon path to your logo
favicon: /images/links/favicon.svg

# canvas
canvasbg:
  enabled: false
  color:
  opacity:
  count:

# personal links
## links icon base folder
linkiconbase: /images/links/
## array of links
links:
  - name: twitter
    link: https://twitter.com/regamian
    icon: twitter.png
  - name: github
    link: https://github.com/zhangluka
    icon: github.png

# pagination
pagination:
  prev_text: '<'
  next_text: '>'

topindex_generator:
  per_page: 10
  order_by: -date

# whether to display `CC BY-SA 4.0` declaration
declaration: false

# comment
waline:
  enabled: true
  serverURL:
  placeholder:
  avatar:
  emoji:
    bilibili: true
    qq: true
    tieba: true
    twitter: true
    alus: true
    weibo: true

# footer
## for users in China
icp:
## visitor counter
counter:
  enabled: false

# google site verification
verimeta: true
